// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorCustomReportApp.Models
{
    public partial class Province
    {
        public Province()
        {
            Store = new HashSet<Store>();
        }

        public int Id { get; set; }
        public string ProvinceCode { get; set; }
        public string ProvinceName { get; set; }

        public virtual ICollection<Store> Store { get; set; }
    }
}