// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorCustomReportApp.Models
{
    public partial class Store
    {
        public Store()
        {
            StoreEmployee = new HashSet<StoreEmployee>();
            StoreProduct = new HashSet<StoreProduct>();
        }

        public int Id { get; set; }
        public string StoreNumber { get; set; }
        public string StoreName { get; set; }
        public int? ProvinceId { get; set; }

        public virtual Province Province { get; set; }
        public virtual ICollection<StoreEmployee> StoreEmployee { get; set; }
        public virtual ICollection<StoreProduct> StoreProduct { get; set; }
    }
}